
const ApiKey = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlMWMyYWE0NWUzZjA5Zjg3N2JhOWNlMmJmMTZjOWQwMCIsInN1YiI6IjY1OWQ4NzRlZmM1ZjA2MDE0YWNiMzZkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.EORNcPkv_zd0yo5vOq5jZOz7OzMyJ7mn51HEc_clEiI'
/*tiken de autorizacio*/
export { ApiKey };